// ============================================
// AA MD Bot - AI Auto Reply
// Owner sets instructions paragraph once →
// bot uses AI to auto-reply incoming DMs
// Disclaimer appended to every AI response
// ============================================

import axios from 'axios';

const CHAT_URL = 'https://text.pollinations.ai/openai';

// One-shot AI call using owner's custom instructions as system prompt
export async function aiAutoReply(userMsg, instructions) {
  const systemPrompt =
    instructions +
    '\n\nIMPORTANT: Write in plain text only. No asterisks, no markdown symbols, no hashtags, no bullet dashes. Be concise and professional.';

  const { data } = await axios.post(CHAT_URL, {
    model: 'openai',
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user',   content: userMsg },
    ],
    temperature: 0.6,
    max_tokens: 400,
  }, {
    headers: { 'Content-Type': 'application/json' },
    timeout: 25000,
  });

  const reply = data?.choices?.[0]?.message?.content?.trim();
  if (!reply) throw new Error('No response');

  // Strip any leftover markdown the AI snuck in
  const clean = reply
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/#{1,6}\s+/g, '')
    .replace(/`{1,3}(.*?)`{1,3}/gs, '$1')
    .replace(/_{2}(.*?)_{2}/g, '$1')
    .trim();

  return clean + '\n\n_(Note: This reply was generated by AI on behalf of the owner)_';
}

export default {
  command: 'autoai',
  alias: ['aireply', 'aiautoreply'],
  description: 'Auto-reply to DMs using AI with your custom instructions',
  category: 'gb',
  ownerOnly: true,
  usage: '.autoai on | .autoai off | .autoai instructions <paragraph> | .autoai status',

  async execute({ args, reply, react, sessionSettings }) {
    const sub = (args[0] || '').toLowerCase();

    // ── STATUS ─────────────────────────────────────────────────────────────────
    if (!sub || sub === 'status' || sub === 'info') {
      const on   = sessionSettings.get('aiAutoReply');
      const inst = sessionSettings.get('aiInstructions');
      return reply(
        `🤖 *AI Auto-Reply Status*\n\n` +
        `Status: *${on ? 'ON ✅' : 'OFF ❌'}*\n\n` +
        `Instructions:\n${inst ? `_"${inst.slice(0, 200)}${inst.length > 200 ? '…' : ''}"_` : '_Not set yet_'}\n\n` +
        `━━━━━━━━━━━━━━\n` +
        `*Commands:*\n` +
        `▸ .autoai on — Enable\n` +
        `▸ .autoai off — Disable\n` +
        `▸ .autoai instructions <paragraph> — Set AI instructions\n` +
        `▸ .autoai status — Check status\n\n` +
        `*Example instructions:*\n` +
        `_.autoai instructions I am Ahsan, a software developer from Pakistan. Reply professionally to my contacts in their language. Keep replies short and polite._\n\n` +
        `> 🤖 *AA MD Bot*`
      );
    }

    // ── ON ─────────────────────────────────────────────────────────────────────
    if (sub === 'on' || sub === 'enable') {
      const inst = sessionSettings.get('aiInstructions');
      if (!inst) {
        return reply(
          `⚠️ *Set instructions first!*\n\n` +
          `Before enabling, give AI a paragraph so it knows how to reply:\n\n` +
          `*.autoai instructions* I am Ahsan, reply professionally...\n\n` +
          `> 🤖 *AA MD Bot*`
        );
      }
      sessionSettings.set('aiAutoReply', true);
      await react('✅');
      return reply(
        `✅ *AI Auto-Reply ENABLED*\n\n` +
        `Anyone who DMs you will get an AI-generated reply.\n` +
        `Use *.autoai off* to stop.\n\n` +
        `> 🤖 *AA MD Bot*`
      );
    }

    // ── OFF ────────────────────────────────────────────────────────────────────
    if (sub === 'off' || sub === 'disable') {
      sessionSettings.set('aiAutoReply', false);
      await react('✅');
      return reply(`❌ *AI Auto-Reply DISABLED.*\n\n> 🤖 *AA MD Bot*`);
    }

    // ── SET INSTRUCTIONS ───────────────────────────────────────────────────────
    if (sub === 'instructions' || sub === 'inst' || sub === 'set') {
      const text = args.slice(1).join(' ').trim();
      if (!text) {
        return reply(
          `❌ *Provide your instructions paragraph.*\n\n` +
          `Example:\n` +
          `_.autoai instructions I am Ahsan Ali, a developer. Reply in Urdu or English based on the sender. Keep replies short and professional._\n\n` +
          `> 🤖 *AA MD Bot*`
        );
      }
      sessionSettings.set('aiInstructions', text);
      await react('✅');
      return reply(
        `✅ *AI Instructions Saved!*\n\n` +
        `"${text.slice(0, 200)}${text.length > 200 ? '…' : ''}"\n\n` +
        `Now run *.autoai on* to enable.\n\n` +
        `> 🤖 *AA MD Bot*`
      );
    }

    return reply(`❓ Unknown option. Use: *.autoai on/off/instructions/status*\n\n> 🤖 *AA MD Bot*`);
  },
};
