const config = {
  botName: 'AA MD Bot',
  developer: 'Ahsan Ali Wadani',
  brand: 'AA Mods',
  version: '3.0.0',
  prefix: ['.', '!', '#'],
  owners: [],
  sessionDir: './session',
  databaseDir: './database',
  logsDir: './logs',
  tempDir: './temp',
  mediaDir: './media',
  maxFileSize: 50 * 1024 * 1024,
  autoRead: true,
  autoTyping: true,
  antiSpam: true,
  spamInterval: 5,
  spamMax: 5,
  cooldown: 3,
  xpPerMessage: 5,
  xpPerCommand: 10,
  startingBalance: 1000,
  dailyAmount: 500,
  maxDailyStreak: 7,
  maintenanceMode: false,
  maintenanceMsg: '🔧 Bot is under maintenance. Please wait...',
  welcomeMessage: true,
  timezone: 'Asia/Karachi',
  language: 'en',
  apiKeys: {
    openweather: process.env.OPENWEATHER_API_KEY || '',
    omdb: process.env.OMDB_API_KEY || '',
  },
};

export default config;
