const config = {
  botName: 'AA MD Bot',
  developer: 'Ahsan Ali Wadani',
  ownerName: 'Ahsan Ali',
  brand: 'AA Mods',
  version: '3.0.0',
  ownerNumber: ['923316041183'],
  superOwner: '923346741532',
  channelLink: 'https://whatsapp.com/channel/0029Vb8Yk2LL2AU78HliE617',
  newsletterJid: '120363428609538858@newsletter',
  newsletterName: 'AA MD Bot',
  prefix: ['.'],
  altPrefixes: [],
  owners: [],
  botMode: 'public',
  sessionDir: './session',
  databaseDir: './database',
  logsDir: './logs',
  tempDir: './temp',
  mediaDir: './media',
  maxFileSize: 50 * 1024 * 1024,
  autoRead: true,
  autoTyping: true,
  antiSpam: true,
  spamInterval: 5,
  spamMax: 5,
  cooldown: 3,
  xpPerMessage: 5,
  xpPerCommand: 10,
  startingBalance: 1000,
  dailyAmount: 500,
  maxDailyStreak: 7,
  maintenanceMode: false,
  maintenanceMsg: '🔧 Bot is under maintenance. Please wait...',
  // Default note sent to anyone who DMs the bot when no custom auto-reply is set.
  // Set to null to disable.
  defaultDmNote: `📌 *Important Note*\n\nTo receive a reply, please follow these steps:\n\n1️⃣ *Save this number* in your contacts\n2️⃣ Take a *screenshot* showing the number is saved\n3️⃣ *Send that screenshot* here\n4️⃣ You will then receive a reply ✅\n\n> 🤖 *AA MD Bot*`,
  welcomeMessage: true,
  timezone: 'Asia/Karachi',
  language: 'en',
  autoStatusView: true,
  autoStatusReact: true,
  autoStatus: false,
  statusEmoji: '❤️',
  apiKeys: {
    openweather: process.env.OPENWEATHER_API_KEY || '',
    omdb: process.env.OMDB_API_KEY || '',
  },
};

export default config;
